### PR TITLE
Update text translation

### PR DESCRIPTION
**Pull request by toanredweb**

### CODE REVIEW

**Comment by huynhngocgiau** [comment]
not fully updated yet
image
image

**Comment by VanTrieuThanh** [comment]
help me check on the endpoint live site and dev branch 
Campaign - filter 
image

Content
 image

**Comment by huynhngocgiau** [comment]
Conflicted a @toanredweb

**Comment by huynhngocgiau** [comment]
I can't test, I will check after this problem is fixed @toanredweb @kakahuy113 
image

**Comment by kakahuy113** [comment]
e @huynhngocgiau ask c @thaoredweb help you remove dam for test dma i still find a solution

**Comment by huynhngocgiau** [comment]
> e @huynhngocgiau ask c @thaoredweb help you remove dam for test dma i still find a solution
I'm check

**Comment by huynhngocgiau** [comment]
Thai
image
image

Missing translate to FR, Croatia

**Comment by huynhngocgiau** [comment]
has updated 
image

**Pull request merged**
